root         = "."
testdata_dir = "testdata"
tmp_dir      = "tmp"

[build]
  args_bin          = []
  bin               = "./tmp/main"
  cmd               = "make build-server"
  delay             = 1000
  exclude_dir       = ["assets", "testdata", "tmp", "vendor"]
  exclude_file      = ["assets/output.css"]
  exclude_regex     = ["_test.go"]
  exclude_unchanged = false
  follow_symlink    = false
  full_bin          = ""
  include_dir       = []
  include_ext       = ["css", "go", "html", "js", "tmpl", "tpl"]
  include_file      = []
  kill_delay        = "10s"
  log               = "build-errors.log"
  poll              = false
  poll_interval     = 0
  rerun             = false
  rerun_delay       = 500
  send_interrupt    = false
  stop_on_error     = false

[color]
  app     = ""
  build   = "yellow"
  main    = "magenta"
  runner  = "green"
  watcher = "cyan"

[log]
  main_only = false
  time      = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll      = true
