services:
  workout-tracker-assets:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: builder-frontend
    volumes:
      - asset-volume:/app/assets
      - ../views:/app/views
      - ../frontend/src:/app/frontend/src
    tty: true

  workout-tracker:
    extends:
      file: ./docker-compose.base.yaml
      service: workout-tracker
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      target: builder-backend
    container_name: wt-app-dev
    ports:
      - 8090:8090
    volumes:
      - asset-volume:/app/assets
      - cache-volume:/root/.cache
      - ../cmd:/app/cmd
      - ../pkg:/app/pkg
      - ../vendor:/app/vendor
      - ../views:/app/views
      - ../translations:/app/translations
    environment:
      - APP_ENV=development
      - WT_JWT_ENCRYPTION_KEY=dev-secret-key
